
server:
  port: 8022
  servlet:
    context-path: /api
    session:
      timeout: 86400 # session

spring:
  application:
    name: sp-22-apiencrypt
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

encrypt:
  body:
    aes-key: 12345678 #AES加密秘钥-8位以上
    des-key: 12345678 #DES加密秘钥-8位以上



