
server:
  port: 8015

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8066/mycat_db1?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/db1?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: 123456