server:
  port: 8018
  servlet:
    context-path: /db
    session:
      timeout: 86400 # session

spring:
  application:
    name: sp-18-shardingsphere
  profiles:
    active: dev1
  main:
    allow-bean-definition-overriding: true
