
# shardingsphere 分表不分库
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/xuan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
      names: master
    props:
      sql:
        show: true
    sharding:
      tables:
        tb_sys_user:
          actual-data-nodes: master.tb_sys_user$->{0..2}
          table-strategy:
            hint:
              algorithm-class-name: com.hins.sp18shardingsphere.config.HintTableShardingAlgorithm
      default-table-strategy:
        standard:
          sharding-column: id
          precise-algorithm-class-name: com.hins.sp18shardingsphere.config.PreciseModuloTableShardingAlgorithm




# PageHelper 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# 日志
logging:
  pattern:
    console: "%d - %msg%n"
  level:
    org.springframework:
      security: info
  #file: logs/mint-parking.log
  config: classpath:logback-spring.xml


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hins.sp18shardingsphere.*.entity
  global-config:
    db-config:
      #刷新mapper 调试神器
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 3
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
      #自定义SQL注入器
      #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  ##logging
  logging:
    level: debug


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

